### ISSUE TITLE
Icon trimmed in selected menu

### ISSUE THREAD

**Issue by soorajcodeares** [Kwasow/BottomNavigationCircles-Android#7]
![Screenshot_20220422-074639](https://user-images.githubusercontent.com/100760103/164619305-570f4bf0-2ac0-4300-8c50-f025d9302dd0.png)

**Comment by Kwasow** [comment]
Hi, thanks for reporting the issue! Is it possible for you to create a minimal proof of concept app that shows the issue? Does it appear on only one device or on different ones?

**Comment by soorajcodeares** [comment]
Here is a demo source code for reference. The issue seems regardless of device, android version or number of menus
[Demos.zip](https://github.com/Kwasow/BottomNavigationCircles-Android/files/8553331/Demos.zip)

**Comment by Kwasow** [comment]
Thanks! I'll look into it

**Comment by Kwasow** [comment]
It seems that the issue is connected to the Material library version `1.5.0` and higher. I've come up with a fix and it is available in on the main branch. If I don't find any issues with it I'll release a new version of the library, that inludes the fix. Thank you very much for your help on the issue!
